services:
  mongo:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27019/mern
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  mongo-data:
